/** Standard error codes returned to clients. */
export const ErrorCodes = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_LOCKED: 'ROOM_LOCKED', // game already started/ended
  ALREADY_IN_ROOM: 'ALREADY_IN_ROOM',
  NOT_IN_ROOM: 'NOT_IN_ROOM',
  INVALID_CLAIM: 'INVALID_CLAIM',
  PRIZE_ALREADY_AWARDED: 'PRIZE_ALREADY_AWARDED',
  PLAYER_DISQUALIFIED: 'PLAYER_DISQUALIFIED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  INTERNAL: 'INTERNAL',
  GAME_NOT_STARTED: 'GAME_NOT_STARTED',
  NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
