export const GAME_CONSTANTS = {
  TOTAL_NUMBERS: 90,
  ROWS_PER_TICKET: 3,
  COLS_PER_TICKET: 9,
  NUMBERS_PER_TICKET: 15,
  NUMBERS_PER_ROW: 5,
  MIN_PLAYERS_TO_START: 2,
  MIN_CALL_INTERVAL_MS: 2000,
  MAX_CALL_INTERVAL_MS: 20_000,
  EARLY5_COUNT: 5,
  ROOM_CODE_LENGTH: 6,
} as const;

export const RATE_LIMITS = {
  CLAIM_PER_SECOND: 3,
  START_PER_SECOND: 1,
  CONFIGURE_PER_SECOND: 2,
} as const;
